### ISSUE TITLE
Can you upload the sample csv data file?

### ISSUE THREAD

**Issue by shadzzz90** [fengjiqiang/LSTM-Wind-Speed-Forecasting#1]
Hi Jacob,

I am trying to understand your code, can you upload a sample csv datafile?

**Comment by scchess** [comment]
Agreed.

**Comment by fengjiqiang** [comment]
> Hi Jacob,
> 
> I am trying to understand your code, can you upload a sample csv datafile?

**Comment by fengjiqiang** [comment]
> Hi Jacob,
> 
> I am trying to understand your code, can you upload a sample csv datafile?

https://github.com/fengjiqiang/LSTM-Wind-Speed-Forecasting/tree/master/data
