### ISSUE TITLE
data folder is not found.

### ISSUE THREAD

**Issue by MeyyammaiMeyyappan** [fengjiqiang/LSTM-Wind-Speed-Forecasting#2]
You have given ../data/*.gz but there's no folder named data found here.
Can you please send the dataset  or source to download the dataset
Thanks!

**Comment by fengjiqiang** [comment]
> You have given ../data/*.gz but there's no folder named data found here.
> Can you please send the dataset or source to download the dataset
> Thanks!

https://github.com/fengjiqiang/LSTM-Wind-Speed-Forecasting/tree/master/data
